import { Inter } from "next/font/google"
import "./globals.css"
// import DashboardNavigation from "@/components/navigation/DashboardNavigation"
// import FloatingFeedbackButton from "@/components/ui/FloatingFeedbackButton"
import TokenRefreshHandler from "@/components/auth/TokenRefreshHandler"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <DashboardNavigation /> */}
        <TokenRefreshHandler />
        {children}
        {/* <FloatingFeedbackButton /> */}
      </body>
    </html>
  )
}
